WIP 54 add more stats to summary
DistributedCollective/FastBTC pull request #59
Opened 2021-04-19 10:26 UTC by Bitcoinera

Missing a DB full of data to finish testing

2021-04-19 11:46 UTC, Bitcoinera commented
Looking good

![image](https://user-images.githubusercontent.com/40721795/115231260-a6d08280-a115-11eb-8753-6a535267e682.png)

2021-04-20 12:05 UTC, ztane commented on models/transaction.js
> +            return res ? res['COUNT(*)'] : 0;
does this actually work? I think it should just use `SELECT COUNT(*) AS ct FROM ...` in the query, and then `return res ? res.ct : 0;`

2021-04-20 12:05 UTC, ztane commented on models/transaction.js
> +            return res || 0;
This as well :D

2021-04-20 12:06 UTC, ztane commented
Also, are those really BTC or satoshis?

2021-04-20 13:00 UTC, Bitcoinera commented
> Also, are those really BTC or satoshis?

Yeah, well spotted. Turns out we were storing the transactions with their values in sats

2021-04-20 13:26 UTC, Bitcoinera commented
Should be good now!

2021-04-20 16:46 UTC, jamiemadrox779 requested changes
dont want socket.io to be downgraded

2021-04-21 10:23 UTC, Bitcoinera commented
> dont want socket.io to be downgraded

OK, fixed

2021-04-24 17:58 UTC, merged